### ISSUE TITLE
App keeps reloading and won't stop 

### ISSUE THREAD

**Issue by jimmymarks** [epicweb-dev/full-stack-foundations#99] opened 2024-09-11 19:38 UTC
I followed the instructions for setup and got all the way to npm start in the terminal. I got the `🐨  Let's get learning!` and the prompts with the URLs for the app, but when I open it in the browser, the app loads, and reloads, and never finishes loading...not sure why. My attempts to try and figure out what was hanging it or why it felt the need to keep building and rebuilding didn't give me much. 

- **Browser**: Version 128.0.6613.120 (Official Build) (arm64) [Note: This was true in every browser, but this is the one I use most]
- **OS**: MacOS Sonoma Version 14.6.1 (23G93)
- **git** --version git version 2.39.3 (Apple Git-146)
- **node** --version v20.16.0
- **npm** --version 10.8.1

**Comment by kentcdodds** [comment] 2024-09-13 21:04
I think I know what bug this could be. Does your browser block cookies?

**Comment by jimmymarks** [comment] 2024-09-18 17:44
Hi, @kentcdodds  – 

No, I'm only blocking cookies in Incognito Mode.

**Comment by jimmymarks** [comment] 2024-09-18 18:24
Hi, @kentcdodds – 

I took a screengrab of the offending code here. Seems like it can't establish `initialPathname`? This is true for me in every single browser I use, incognito or not. 

![2024-09-18_14-22-48](https://github.com/user-attachments/assets/51e22b72-cec4-4883-afdb-1acbc995a8c2)

**Comment by kentcdodds** [comment] 2024-09-18 22:45
Ah that's a real bummer... I'm not so sure what that could possibly be caused by. Looks like some pretty edge-case code you're ending up in. Definitely not what I thought was causing this... Hmmm...

Could you tell me what the error message says?

**Comment by jimmymarks** [comment] 2024-09-23 17:19
Console error:

```
Initial URL (undefined) does not match URL at time of hydration (/), reloading page...
```

**Comment by jimmymarks** [comment] 2024-09-23 17:20
One more, at the first moment after reload begins: 

```
Uncaught (in promise) SecurityError: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.
```

**Comment by kentcdodds** [comment] 2024-09-24 03:02
That last error is fine.

This error though:

> Initial URL (undefined) does not match URL at time of hydration (/), reloading page...

That is concerning and seems to be an issue in React Router / Remix. Do you think you could come to [my next Office Hours](https://kcd.im/office-hours) so we can debug the issue together? It's possible the output of that meeting would be an issue filed on React Router.

**Comment by kentcdodds** [comment] 2024-09-24 03:03
The tricky thing is I can't reproduce your issue so I need to be able to debug with you on your machine.

**Comment by kentcdodds** [comment] 2024-11-05 17:11
As I cannot reproduce this myself I'm going to close this issue.

**Closed as completed by kentcdodds** 2024-11-05 17:11 UTC
